import React from 'react'

export const jwels= [{
    id            : 1,
    image          : "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Z29sZCUyMGpld2VsbGVyeXxlbnwwfHwwfHx8MA%3D%3D",
    productname    : "Gold Antique Jewellery",
    price          :  "Starts form 680/-",
    description    :  " 30% off on December sale.. ",
   },
   {
    id            : 2,
    image          : "https://media.istockphoto.com/id/1276740597/photo/indian-traditional-gold-necklace.jpg?s=612x612&w=0&k=20&c=OYp1k0OVJObYq9hqVK_r6NwYa_W54km4nya1R-ovIUY=",
    productname    : "South Indian Jwellery",
    price          :  "Starts form 890/-",
    description    :  "30% off on December sale..",
   },
   {
    id            : 3,
    image          : "https://media.istockphoto.com/id/611997004/photo/indian-traditional-gold-necklace.jpg?s=612x612&w=0&k=20&c=pKD2qzNYriUmQVh425jA9Kaa4n2lFQmIuHVAOMSvqgs=",
    productname    : "Gold Antique Jewellery",
    price          : "Starts form 500/-" ,
    description    :  "Order now to get 20% off.",
   },
   {
    id            : 4,
    image          : "https://media.istockphoto.com/id/672123610/photo/indian-traditional-gold-necklace.jpg?s=612x612&w=0&k=20&c=Jwr4_p-FcmCJ_WvfdYQyGlkqhtg3NIVSbHLSD0mxJJU=",
    productname    : "Navratna Models",
    price          :  "Starts form 1300/-",
    description    :  "Order now to get exclusive offers.",
   },
   {
    id            : 5,
    image          : "https://media.istockphoto.com/id/486579128/photo/indian-jewellery.jpg?s=612x612&w=0&k=20&c=Dm5MUSjHXvKH_Jz7sN27lrNBRu7pnAYGz9ELiKCbwG8=",
    productname    : "South Indian Jwellery",
    price          :  "Starts form 800/-",
    description    :  "Order now to get 30% off..",
   },
//    {
//     id            : 6,
//     image          : "",
//     productname    : "",
//     price          :  "",
//     description    :  "",
//    },
//    {
//     id            : 7,
//     image          : "",
//     productname    : "",
//     price          :  "",
//     description    :  "",
//    },
//    {
//     id            : 8,
//     image          : "",
//     productname    : "",
//     price          :  "",
//     description    :  "",
//    },
//    {
//     id            : 9,
//     image          : "",
//     productname    : "",
//     price          :  ,
//     description    :  ,
//    },
//    {
//     id            : 10,
//     image          : "",
//     productname    : "",
//     price          :  ,
//     description    :  ,
//    },
//    {
//     id            : 11,
//     image          : "",
//     productname    : "",
//     price          :  ,
//     description    :  ,
//    },
//    {
//     id            : 12,
//     image          : "",
//     productname    : "",
//     price          :  ,
//     description    :  ,
//    },
//    {
//     id            : 13,
//     image          : "",
//     productname    : "",
//     price          :  ,
//     description    :  ,
//    },
//    {
//     id            : 14,
//     image          : "",
//     productname    : "",
//     price          :  ,
//     description    :  ,
//    },
//    {
//     id            : 15,
//     image          : "",
//     productname    : "",
//     price          :  ,
//     description    :  ,
//    },
//    {
//     id            : 16,
//     image          : "",
//     productname    : "",
//     price          :  ,
//     description    :  ,
//    },
//    {
//     id            : 17,
//     image          : "",
//     productname    : "",
//     price          :  ,
//     description    :  ,
//    },
//     {
//     id            : 18,
//     image          : "",
//     productname    : "",
//     price          :  ,
//     description    :  ,
//    },
//     {
//     id            : 19,
//     image          : "",
//     productname    : "",
//     price          :  ,
//     description    :  ,
//    },
//     {
//     id            : 20,
//     image          : "",
//     productname    : "",
//     price          :  ,
//     description    :  ,
//    }

]